import EventBus from '../Events/EventBus.js';

/**
 * LocalizationManager handles multi-language support.
 * It listens for LANGUAGE_CHANGED events and prepares translations.
 */
class LocalizationManager {
    constructor() {
        this.currentLanguage = localStorage.getItem('gameLanguage') || 'KR';
        this.init();
    }

    init() {
        this.dictionary = {
            'KR': {
                'nav_territory': '영지',
                'nav_gacha': '뽑기',
                'nav_party': '편성',
                'nav_dungeon': '던전',
                'nav_arena': '아레나',
                'nav_raid': '레이드',
                'nav_dungeon_forest': '저주받은 숲',
                'nav_dungeon_graveyard': '언데드 묘지',
                'nav_dungeon_swamp': '늪지대',
                'nav_dungeon_lava': '용암 지대',
                'nav_dungeon_winter': '겨울의 나라',
                'menu_roster': '용병 도감',
                'menu_shop': '상점',
                'menu_equipment': '장비창',
                'menu_pets': '펫 보관함',
                'menu_npc_hire': 'NPC 고용',
                'menu_messiah': '메시아 권능 관리',
                'menu_structures': '방어 시설 관리',
                'menu_achievements': '업적',
                'menu_monster_codex': '몬스터 도감',
                'menu_cooking': '요리하기',
                'menu_fishing': '낚시 관리',
                'menu_alchemy': '연금술 관리',
                'menu_music': '집중 모드 & 음반 구입',
                'patch_notes_title': '📋 패치 내역',
                'toast_preparing': '준비 중입니다 🔧',
                'toast_gold_shortage': '골드가 부족합니다! 💰',
                'toast_party_not_full': '6명의 용병을 편성해주세요',
                'toast_building_upgraded': '건물을 강화했습니다! ✨',
                'toast_building_demolished': '건물을 철거했습니다. 💨',
                'toast_building_constructed': '건물을 건설했습니다! ✨',
                'toast_language_changed': '언어가 한국어로 변경되었습니다.',
                'confirm_exit_combat': '전투가 진행 중입니다. 정말로 나가시겠습니까?',
                'confirm_forfeit_combat': '전투를 포기하고 나가시겠습니까?',
                'confirm_demolish': '건물을 철거하시겠습니까? 🔨',
                'ui_tab_emoji': '🎒 이모지',
                'ui_tab_gear': '⚔️ 장비',
                'ui_filter_all': '전체',
                'ui_filter_weapon': '무기',
                'ui_filter_armor': '방어구',
                'ui_filter_necklace': '목걸이',
                'ui_filter_ring': '반지',
                'ui_btn_equip': '장착',
                'ui_btn_discard': '버리기',
                'ui_btn_upgrade': '강화',
                'ui_btn_demolish': '철거',
                'ui_btn_construction_exit': '건축 종료 (ESC)',
                'ui_construction_hint': '마우스 우클릭 / 길게 터치: 시설물 배치',
                'building_bank': '은행',
                'building_factory': '공장',
                'building_church': '성당',
                'building_camp': '캠프',
                'building_tree': '나무',
                'building_castle': '성',
                'shop_title': '🏛️ 로얄 상점 (ROYAL SHOP)',
                'shop_category_tickets': '🎫 입장권',
                'shop_category_charms': '✨ 부적',
                'shop_category_food': '🍰 음식',
                'shop_category_fishing': '🎣 낚시',
                'shop_category_alchemy': '⚗️ 연금',
                'shop_category_materials': '🌿 재료',
                'item_name_emoji_coin': '골드 코인',
                'item_name_emoji_gem': '젬스톤',
                'item_name_emoji_brick': '벽돌',
                'item_name_emoji_meat': '몬스터 고기',
                'item_name_emoji_wood': '나무 원목',
                'item_name_emoji_herb': '마법 허브',
                'item_name_emoji_ticket': '언데드 묘지 입장권',
                'item_name_swampland_ticket': '늪지대 입장권',
                'item_name_lava_field_ticket': '용암 지대 입장권',
                'item_name_winter_land_ticket': '겨울의 나라 입장권',
                'item_name_emoji_clover': '클로버',
                'item_name_emoji_bone': '뼈',
                'item_name_turret_bowgun': '보우건 터렛',
                'item_name_healing_turret': '힐링 터렛',
                'item_name_emoji_burger': '햄버거 참',
                'item_name_emoji_fireworks': '화염 저항의 참',
                'item_name_emoji_sparkler': '번개 저항의 참',
                'item_name_emoji_koinobori': '냉기 저항의 참',
                'item_name_emoji_divine_essence': '전능의 정수',
                'item_name_eternal_ice': '영원한 얼음',
                'item_name_emoji_candle': '양초',
                'item_name_food_choco_parfait': '초코 파르페',
                'item_name_food_strawberry_cake': '딸기 케이크',
                'item_name_bamboo_fishing_rod': '대나무 낚시대',
                'item_name_alchemy_tool_basic': '평범한 연금도구',
                'item_name_atk_potion': '공격력 포션',
                'item_name_def_potion': '방어력 포션',
                'item_name_mAtk_potion': '마법공격력 포션',
                'item_name_mDef_potion': '마법방어력 포션',
                'item_name_mackerel': '고등어',
                'item_name_herring': '청어',
                'item_name_squid': '오징어',
                'item_name_wood_sword': '우드 소드',
                'item_name_wood_armor': '우드 아머',
                'item_name_wood_wand': '우드 완드',
                'shop_buy': '구매',
                'shop_buy_confirm': '{0}을(를) {1}개 구매하시겠습니까?',
                'shop_buy_success': '{0} {1} 구매 완료! ✨',
                'shop_low_resources': '자원이 부족합니다! ⚠️',

                // Equipment Crafting
                'ui_craft_title': '⚔️ 장비 제작 (EQUIPMENT CRAFTING)',
                'ui_craft_list_header': '[제작 가능 목록]',
                'ui_owned_growth_header': '[보유 중인 성장 장비]',
                'ui_craft_none_selected': '선택된 장비 없음',
                'ui_craft_detail_btn': '상세 정보 보기',
                'ui_craft_destroy_btn': '장비 파괴',
                'ui_craft_footer_tip': '* 무기는 데미지를 입힐 때, 방어구는 데미지를 받을 때 성장합니다.',
                'ui_craft_destroy_confirm': '[{0} LV.{1}]을 파괴하시겠습니까?<br><span style="color: #ef4444; font-size: 11px;">* 이 작업은 되돌릴 수 없습니다.</span>',
                'ui_craft_success': '{0} 제작 성공! ✨',
                'ui_craft_destroy_success': '{0} 파괴 완료. 💥',
                'ui_craft_btn': '제작',
                'ui_craft_owned_count': '보유: {0}',
                'ui_craft_equipped': '장착 중: {0}',
                'ui_craft_in_inventory': '[보유 중]',
                'ui_craft_unique_growth': '고유 성장 장비',
                'ui_craft_growth_tip': '* 이 장비는 전투를 통해 성장하며 추가 옵션이 개방됩니다.',

                // Pet Storage
                'ui_pet_storage_title': '🐾 펫 보관함 (PET STORAGE)',
                'ui_pet_empty_selection': '펫을 선택하세요',
                'ui_pet_stat_atk': '공격력',
                'ui_pet_stat_mAtk': '마법공격력',
                'ui_pet_stat_speed': '이동속도',
                'ui_pet_stat_atkSpd': '공격속도',
                'ui_pet_feed_btn': '고기 먹이기',
                'ui_pet_feed_cost': '(소모: {0}개)',
                'ui_pet_passive_header': '[특수 패시브: {0}]',
                'ui_pet_low_meat': '몬스터 고기가 부족합니다! 🍖',
                'ui_pet_lvl_up_success': '{0} 레벨 업! ✨',
                'pet_name_dog_pet': '도그펫',
                'pet_name_wolf_pet': '울프펫',
                'pet_name_owl_pet': '올펫',
                'pet_passive_name_dog_pet': '충직한 보물탐험가',
                'pet_passive_desc_dog_pet': '던전에서 아이템 드랍율이 5% 상승합니다.',
                'pet_passive_name_wolf_pet': '늑대의 포효',
                'pet_passive_desc_wolf_pet': '아군 전체의 공격력이 5% 상승합니다.',
                'pet_passive_name_owl_pet': '지혜의 눈',
                'pet_passive_desc_owl_pet': '아군 전체의 마법 공격력이 5% 상승합니다.',
                'ui_roster_owned': '보유: {0}',
                'ui_skin_selector_title': '스킨 선택 - {0}',
                'ui_skin_default': '기본 외형',
                'ui_skin_equipped': '[착용 중]',
                'ui_skin_owned': '보유 중',
                'ui_skin_buy_confirm': '{0} 스킨을 {1}다이아에 구매하시겠습니까?',
                'ui_skin_buy_success': '구매 완료!',
                'ui_roster_stats': 'DETAILED STATISTICS',
                'ui_roster_skills': 'SKILLS & ULTIMATE',
                'ui_btn_theme_skin': '[테마 스킨 교체]',
                'char_nickle_name': 'Nickle (니클)',
                'char_nickle_personality': '여우 수인족 출신의 늙은 베테랑. "나 때는 말이야~"를 입에 달고 사는 꼰대. 늙은이 취급 당하는 걸 싫어하지만, 귀여운 외모 때문에 아무도 그를 어르신으로 안 본다.',
                'char_nickle_skill_name': 'TacticalCommand',
                'char_nickle_skill_desc': '자신과 무작위 아군 1명의 모든 기본 행동(공격, 힐, 버프) 수치를 10초간 50% 강화합니다. (재사용 대기시간 25초)',
                'char_nickle_ult_name': '왕년엔 말이야...',
                'char_nickle_ult_desc': '20초간 전성기 시절의 힘을 되찾습니다. 이동 속도 3배 증가 및 5발의 화살을 부채꼴로 동시 발사합니다.',
                'char_nana_name': 'Nana (나나)',
                'char_nana_personality': '평상시엔 쾌활하고 귀엽고 상냥한 소녀 음유시인. 노래부르기를 좋아하고 자신의 팬들을 사랑하는 아이돌이자, 피를 보는 걸 무서워하는 상냥한 소녀입니다. 하지만...',
                'char_nana_skill_name': 'MusicalMagicalCritical',
                'char_nana_skill_desc': '가장 많은 아군과 적군이 뭉친 곳에 하트와 음표를 쏟아붓습니다. 적에게는 마법 공격력 기반의 광역 피해를, 아군에게는 8초간 치명타율 20% 상승 버프를 부여합니다. (재사용 대기시간 12초)',
                'char_nana_ult_name': '피를 다오! 크하하하!',
                'char_nana_ult_desc': '20초간 피에 굶주린 본성을 드러냅니다! 공격력, 공격 속도, 이동 속도, 치명타율, 회피율이 대폭 상승하며 클래스가 전사로 변경됩니다. 변신 종료 후 2초간 수면 상태에 빠집니다.',
                'skin_nickle_fox_name': '여우 아니다 (I\'m not a fox)',
                'skin_nickle_fox_bonus': '전술 지휘 시 공격 속도 +25% 추가 상승',
                'skin_nana_idol_name': '모두의 아이돌',
                'skin_nana_idol_bonus': '뮤지컬매지컬크리티컬 시전 시 아군/적군 양쪽 동시 적용',
            },
            'EN': {
                'nav_territory': 'Territory',
                'nav_gacha': 'Gacha',
                'nav_party': 'Formation',
                'nav_dungeon': 'Dungeon',
                'nav_arena': 'Arena',
                'nav_raid': 'Raid',
                'nav_dungeon_forest': 'Cursed Forest',
                'nav_dungeon_graveyard': 'Undead Graveyard',
                'nav_dungeon_swamp': 'Swampland',
                'nav_dungeon_lava': 'Lava Field',
                'nav_dungeon_winter': 'Winter Land',
                'menu_roster': 'Mercenary Roster',
                'menu_shop': 'Shop',
                'menu_equipment': 'Equipment',
                'menu_pets': 'Pet Storage',
                'menu_npc_hire': 'NPC Hire',
                'menu_messiah': 'Messiah Touch',
                'menu_structures': 'Structures',
                'menu_achievements': 'Achievements',
                'menu_monster_codex': 'Monster Codex',
                'menu_cooking': 'Cooking',
                'menu_fishing': 'Fishing',
                'menu_alchemy': 'Alchemy',
                'menu_music': 'Focus & Music',
                'patch_notes_title': '📋 Patch Notes',
                'toast_preparing': 'Coming Soon 🔧',
                'toast_gold_shortage': 'Not enough gold! 💰',
                'toast_party_not_full': 'Please deploy 6 mercenaries',
                'toast_building_upgraded': 'Building upgraded! ✨',
                'toast_building_demolished': 'Building demolished. 💨',
                'toast_building_constructed': 'Building constructed! ✨',
                'toast_language_changed': 'Language changed to English.',
                'confirm_exit_combat': 'Combat in progress. Do you really want to leave?',
                'confirm_forfeit_combat': 'Give up and leave combat?',
                'confirm_demolish': 'Do you want to demolish this building? 🔨',
                'ui_tab_emoji': '🎒 Emoji',
                'ui_tab_gear': '⚔️ Gear',
                'ui_filter_all': 'Total',
                'ui_filter_weapon': 'Weapon',
                'ui_filter_armor': 'Armor',
                'ui_filter_necklace': 'Necklace',
                'ui_filter_ring': 'Ring',
                'ui_btn_equip': 'Equip',
                'ui_btn_discard': 'Discard',
                'ui_btn_upgrade': 'Upgrade',
                'ui_btn_demolish': 'Demolish',
                'ui_btn_construction_exit': 'Exit Build Mode (ESC)',
                'ui_construction_hint': 'Right Click / Long Press: Place Structure',
                'building_bank': 'Bank',
                'building_factory': 'Factory',
                'building_church': 'Church',
                'building_camp': 'Camp',
                'building_tree': 'Tree',
                'building_castle': 'Castle',
                'shop_title': '🏛️ ROYAL SHOP',
                'shop_category_tickets': '🎫 Tickets',
                'shop_category_charms': '✨ Charms',
                'shop_category_food': '🍰 Food',
                'shop_category_fishing': '🎣 Fishing',
                'shop_category_alchemy': '⚗️ Alchemy',
                'shop_category_materials': '🌿 Mat.',
                'item_name_emoji_coin': 'Gold Coin',
                'item_name_emoji_gem': 'Gemstone',
                'item_name_emoji_brick': 'Brick',
                'item_name_emoji_meat': 'Monster Meat',
                'item_name_emoji_wood': 'Wood Log',
                'item_name_emoji_herb': 'Magic Herb',
                'item_name_emoji_ticket': 'Undead Graveyard Ticket',
                'item_name_swampland_ticket': 'Swampland Ticket',
                'item_name_lava_field_ticket': 'Lava Field Ticket',
                'item_name_winter_land_ticket': 'Winter Land Ticket',
                'item_name_emoji_clover': 'Clover',
                'item_name_emoji_bone': 'Bone',
                'item_name_turret_bowgun': 'Bowgun Turret',
                'item_name_healing_turret': 'Healing Turret',
                'item_name_emoji_burger': 'Burger Charm',
                'item_name_emoji_fireworks': 'Fire Resist Charm',
                'item_name_emoji_sparkler': 'Lightning Resist Charm',
                'item_name_emoji_koinobori': 'Frost Resist Charm',
                'item_name_emoji_divine_essence': 'Divine Essence',
                'item_name_eternal_ice': 'Eternal Ice',
                'item_name_emoji_candle': 'Candle',
                'item_name_food_choco_parfait': 'Choco Parfait',
                'item_name_food_strawberry_cake': 'Strawberry Cake',
                'item_name_bamboo_fishing_rod': 'Bamboo Fishing Rod',
                'item_name_alchemy_tool_basic': 'Basic Alchemy Tool',
                'item_name_atk_potion': 'ATK Potion',
                'item_name_def_potion': 'DEF Potion',
                'item_name_mAtk_potion': 'M.ATK Potion',
                'item_name_mDef_potion': 'M.DEF Potion',
                'item_name_mackerel': 'Mackerel',
                'item_name_herring': 'Herring',
                'item_name_squid': 'Squid',
                'item_name_wood_sword': 'Wood Sword',
                'item_name_wood_armor': 'Wood Armor',
                'item_name_wood_wand': 'Wood Wand',
                'shop_buy': 'Buy',
                'shop_buy_confirm': 'Purchase {0} x{1}?',
                'shop_buy_success': 'Purchased {0} x{1}! ✨',
                'shop_low_resources': 'Not enough resources! ⚠️',

                // Equipment Crafting
                'ui_craft_title': '⚔️ EQUIPMENT CRAFTING',
                'ui_craft_list_header': '[RECIPE LIST]',
                'ui_owned_growth_header': '[OWNED GROWTH EQUIPMENT]',
                'ui_craft_none_selected': 'No equipment selected',
                'ui_craft_detail_btn': 'View Details',
                'ui_craft_destroy_btn': 'Destroy Equipment',
                'ui_craft_footer_tip': '* Weapons grow when dealing damage, Armor grows when taking damage.',
                'ui_craft_destroy_confirm': 'Destroy [{0} LV.{1}]?<br><span style="color: #ef4444; font-size: 11px;">* This action cannot be undone.</span>',
                'ui_craft_success': '{0} Crafted! ✨',
                'ui_craft_destroy_success': '{0} Destroyed. 💥',
                'ui_craft_btn': 'Craft',
                'ui_craft_owned_count': 'Owned: {0}',
                'ui_craft_equipped': 'Equipped: {0}',
                'ui_craft_in_inventory': '[In Inventory]',
                'ui_craft_unique_growth': 'Unique Growth Equipment',
                'ui_craft_growth_tip': '* This equipment grows through combat, unlocking extra options.',

                // Pet Storage
                'ui_pet_storage_title': '🐾 PET STORAGE',
                'ui_pet_empty_selection': 'Select a Pet',
                'ui_pet_stat_atk': 'Attack',
                'ui_pet_stat_mAtk': 'M.Attack',
                'ui_pet_stat_speed': 'Move Speed',
                'ui_pet_stat_atkSpd': 'Attack Speed',
                'ui_pet_feed_btn': 'Feed Meat',
                'ui_pet_feed_cost': '(Cost: {0})',
                'ui_pet_passive_header': '[Special Passive: {0}]',
                'ui_pet_low_meat': 'Not enough monster meat! 🍖',
                'ui_pet_lvl_up_success': '{0} Leveled Up! ✨',
                'pet_name_dog_pet': 'Dog Pet',
                'pet_name_wolf_pet': 'Wolf Pet',
                'pet_name_owl_pet': 'Owl Pet',
                'pet_passive_name_dog_pet': 'Faithful Treasure Hunter',
                'pet_passive_desc_dog_pet': 'Item drop rate +5% in dungeons.',
                'pet_passive_name_wolf_pet': 'Wolf Howl',
                'pet_passive_desc_wolf_pet': 'Party Attack +5%.',
                'pet_passive_name_owl_pet': 'Eye of Wisdom',
                'pet_passive_desc_owl_pet': 'Party Magic Attack +5%.',
                'ui_roster_owned': 'Owned: {0}',
                'ui_skin_selector_title': 'Select Skin - {0}',
                'ui_skin_default': 'Default Appearance',
                'ui_skin_equipped': '[ Equipped ]',
                'ui_skin_owned': 'Owned',
                'ui_skin_buy_confirm': 'Purchase {0} skin for {1} Diamonds?',
                'ui_skin_buy_success': 'Purchase Complete!',
                'ui_roster_stats': 'DETAILED STATISTICS',
                'ui_roster_skills': 'SKILLS & ULTIMATE',
                'ui_btn_theme_skin': '[Change Skin]',
                'char_nickle_name': 'Nickle',
                'char_nickle_personality': 'An old veteran from the Fox-kin tribe. A grumbler who always talks about "back in my day." He hates being treated like an old man, but due to his cute appearance, nobody sees him as an elder.',
                'char_nickle_skill_name': 'Tactical Command',
                'char_nickle_skill_desc': 'Enhances all basic actions (Attack, Heal, Buff) of himself and one random ally by 50% for 10 seconds. (Cooldown: 25s)',
                'char_nickle_ult_name': 'Back In My Day...',
                'char_nickle_ult_desc': 'Regains his peak strength for 20 seconds. Increases movement speed by 3x and fires 5 arrows simultaneously in a fan shape.',
                'char_nana_name': 'Nana',
                'char_nana_personality': 'Usually a cheerful, cute, and kind girl minstrel. An idol who loves singing and her fans, and a gentle girl who is afraid of seeing blood. However...',
                'char_nana_skill_name': 'Musical Magical Critical',
                'char_nana_skill_desc': 'Showers hearts and notes where most allies and enemies are clustered. Deals AoE damage to enemies and grants a 20% Crit Rate buff to allies for 8 seconds. (Cooldown: 12s)',
                'char_nana_ult_name': 'GIVE ME BLOOD! MWAHAHA!',
                'char_nana_ult_desc': 'Reveals her blood-thirsty nature for 20 seconds! ATK, ATK Speed, Movement Speed, Crit Rate, and Evasion are greatly increased, and class changes to Warrior. Falls asleep for 2 seconds after the transformation ends.',
                'skin_nickle_fox_name': "I'm not a fox",
                'skin_nickle_fox_bonus': 'Tactical Command ATK Speed +25% additional increase',
                'skin_nana_idol_name': "Everyone's Idol",
                'skin_nana_idol_bonus': 'Musical Magical Critical applies to both allies and enemies simultaneously',
            }
        };

        console.log(`[LocalizationManager] Initialized with language: ${this.currentLanguage}`);
        
        EventBus.on(EventBus.EVENTS.LANGUAGE_CHANGED, (payload) => {
            this.handleLanguageChange(payload.language);
        });
    }

    handleLanguageChange(lang) {
        this.currentLanguage = lang;
        console.log(`[LocalizationManager] System language updated to: ${lang}`);
        // Optionally save to localStorage if not already done by UI
        localStorage.setItem('gameLanguage', lang);
    }
    /**
     * Get a localized string by key
     * @param {string} key 
     * @param {Array} params Optional replacement parameters
     * @param {string} fallback Optional fallback string if key is not found
     * @returns {string}
     */
    t(key, params = [], fallback = null) {
        let text = fallback !== null ? fallback : key;
        if (this.dictionary[this.currentLanguage] && this.dictionary[this.currentLanguage][key]) {
            text = this.dictionary[this.currentLanguage][key];
        }

        if (params && params.length > 0) {
            params.forEach((p, idx) => {
                text = text.replace(`{${idx}}`, p);
            });
        }
        return text;
    }
}

// Global instance
const localizationManager = new LocalizationManager();
export default localizationManager;
